# -*- coding: utf-8 -*-
"""aula 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YdfiCksuxHBMXOi9G0brA6fCLBOIflAp
"""

# ETE Porto digital
# professor diciplina LPC1
# professor: cloves
# estudante: victor luiz almeida medeiros

print ('ola, ETE PORTO DIGITAL!')