# -*- coding: utf-8 -*-
"""desafio desplugado

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tolc3Tx_v5AOcAZTo3m2WCpx_rfQWonB
"""

nomes = []
age = []

for c in range(0,5):
  nomes.append(input("Digite um nome"))
  age.append(int(input("Digite a idade")))

  for l, v in zip(nomes. age):
    print(l, v)

    age.sort(reverse=true)
    for l in age:
      print(l)
#victor luiz almeida medeiros