# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gm2pwKTGD8wMV2gIPvo8a5jAGoFNIqT5
"""

#1
print ('alo ETE PORTO DIGITAL')

#2
msg = input('Digite um número: ')
print ('O numero escolhido foi: ' + msg)

#3
num1 = float(input ('Digite o primeiro numero'))
num2 = float(input ('Digite o segundo numero'))
soma = (num1+num2)
print ('A soma dos dois números é: ' + str(soma))

#4
nota1 = float (input ('digite a primeira nota: '))
nota2 = float (input ('digite a segundo nota: '))
nota3 = float (input ('digite a terceiro nota: '))
nota4 = float (input ('digite a quarta nota: '))
media = ((nota1+ nota2+nota3+nota4)/4)
print ('A media das notas é: ' + str(media))

#5
num1 = float(input('Escolha o numero em metros: '))
cm = (num1*100)
print ('o numero em centimetros é: ' + str(cm))

#6
raio = float(input('Qual o tamanho do raio?: '))
area = ((raio**2)*3.14)
print ('a area é: ' + str(area)+ 'mm')

#7
b = float(input('qual a base do quadrado?: '))
h = float(input('qual a altura do quadrado?: '))
area = (b*h)
area2 = (area*2)
print ('a area do quadrado é: '+ str(area))
print ('o dobro da area é: '+ str(area2))

#8
hora = float(input('quanto você ganha por hora?: '))
hora2 = float(input('quantas horas trabalha por mês?: '))
salario = (hora*hora2)
print ('você ganha R$'+str(salario)+' por mês')

#9
 F = float(input('diga a temperatura em fahrenheit: ')) 
 C = (F-32)/1.8
 print ('A temperatura em celsius é: ' + str(C))

#10
C = float(input('diga a temperatura em celsius: ')) 
 F = (C*1.8) + 32
 print ('A temperatura em fahrenheit é: ' + str(F))

#11

n1 = int(input('Digite o primeiro numero: \n'))
n2 = int(input('Digite o segundo numero: \n'))
nreal = float(input('Digite o numero Real: \n'))

r1 = n1*2*(n2 / 2)

print ('o produto do dobro do primeiro com metade do segundo = ' + str(r1))

r2 = n1 * 3 + nreal
print ('a soma do triplo do primeiro com o terceiro = '+ str(r2))

r3 = nreal ** 3
print ('o terceiro elevado ao cubo= '+ str(r3))

#12 e 13
altura = float(input('qual sua altura?: '))
x = (72.7*altura)-58
y = (62.1*altura)-44.7
print ('se você for MULHER seu peso ideal é: ' + str(x))
print ('se você for HOMEM seu peso ideal é: ' + str(y))

#14
peixes = int(input('quantos KG tem de peixes?: '))
i = (peixes - 50)
x = i*4
if peixes > 50:
  print('você pagará de multa: ' + str(x))
else: 
  print('Você nao pagará multa')

#15
tamanho = float(input('Qual o tamnho do arquivo em MB?: '))
vel = float(input('qual a velocidade da internet em mbps?: ' ))
tempo = (tamanho * vel) / 60
print ('levará:' + str(tempo) + ' minutos')